bigrule:
  etcd-service:
    host: 
    port: 2379
  service-manager:
    # 启动服务配置
    application:
      model: debug
      host: 
      port: 8081
    # mysql 配置模块
    dbmysql:
      addr: :@tcp(:3306)/?charset=utf8&parseTime=True&loc=Local
      loglevel: warn
    # 系统日志配置模块
    logger:
      path: ./logs/service-manager/
      stdout: true
      level: debug
  authentication:
    # 启动服务配置
    application:
      model: debug
      host: 
      port: 8082
    # mysql 配置模块
    dbmysql:
      addr: 
      loglevel: debug
    # 系统日志配置模块
    logger:
      path: ./logs/authentication/
      stdout: true
      level: debug
    # cookie 配置模块 以下时间都是秒级单位
    cookie:
      mysqlTime: 86400
    # 静态路由
    web-static:
      path: C:
    # 提示信息路径
    response-message:
      path: D:
    #经分系统url
    jf:
      userUrl: http://
      checkUrl: http://12
      csrUrl: 
      roleId: 2
      deptId: 1
      ips: [

      ]
    # prometheus 统计接口列表
    prometheus:
      url: [  ]
